//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBGCCCine.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pelicula", Namespace="http://schemas.datacontract.org/2004/07/WCF_GCCCine.Clases")]
    [System.SerializableAttribute()]
    public partial class Pelicula : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DuracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeliculaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Duracion {
            get {
                return this.DuracionField;
            }
            set {
                if ((object.ReferenceEquals(this.DuracionField, value) != true)) {
                    this.DuracionField = value;
                    this.RaisePropertyChanged("Duracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneroField, value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeliculaID {
            get {
                return this.PeliculaIDField;
            }
            set {
                if ((this.PeliculaIDField.Equals(value) != true)) {
                    this.PeliculaIDField = value;
                    this.RaisePropertyChanged("PeliculaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Funciones", Namespace="http://schemas.datacontract.org/2004/07/WCF_GCCCine.Clases")]
    [System.SerializableAttribute()]
    public partial class Funciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechafuncionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WEBGCCCine.ServiceReference1.Pelicula PeliculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeliculaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int funcionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fechafuncion {
            get {
                return this.FechafuncionField;
            }
            set {
                if ((this.FechafuncionField.Equals(value) != true)) {
                    this.FechafuncionField = value;
                    this.RaisePropertyChanged("Fechafuncion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WEBGCCCine.ServiceReference1.Pelicula Pelicula {
            get {
                return this.PeliculaField;
            }
            set {
                if ((object.ReferenceEquals(this.PeliculaField, value) != true)) {
                    this.PeliculaField = value;
                    this.RaisePropertyChanged("Pelicula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeliculaId {
            get {
                return this.PeliculaIdField;
            }
            set {
                if ((this.PeliculaIdField.Equals(value) != true)) {
                    this.PeliculaIdField = value;
                    this.RaisePropertyChanged("PeliculaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalaId {
            get {
                return this.SalaIdField;
            }
            set {
                if ((this.SalaIdField.Equals(value) != true)) {
                    this.SalaIdField = value;
                    this.RaisePropertyChanged("SalaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int funcionId {
            get {
                return this.funcionIdField;
            }
            set {
                if ((this.funcionIdField.Equals(value) != true)) {
                    this.funcionIdField = value;
                    this.RaisePropertyChanged("funcionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPelicula")]
    public interface IPelicula {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPelicula/GetPeliculas", ReplyAction="http://tempuri.org/IPelicula/GetPeliculasResponse")]
        WEBGCCCine.ServiceReference1.Pelicula[] GetPeliculas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPelicula/GetPeliculas", ReplyAction="http://tempuri.org/IPelicula/GetPeliculasResponse")]
        System.Threading.Tasks.Task<WEBGCCCine.ServiceReference1.Pelicula[]> GetPeliculasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPelicula/GetPelicula", ReplyAction="http://tempuri.org/IPelicula/GetPeliculaResponse")]
        WEBGCCCine.ServiceReference1.Pelicula GetPelicula(int PeliculaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPelicula/GetPelicula", ReplyAction="http://tempuri.org/IPelicula/GetPeliculaResponse")]
        System.Threading.Tasks.Task<WEBGCCCine.ServiceReference1.Pelicula> GetPeliculaAsync(int PeliculaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPelicula/AddPelicula", ReplyAction="http://tempuri.org/IPelicula/AddPeliculaResponse")]
        void AddPelicula(WEBGCCCine.ServiceReference1.Pelicula pelicula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPelicula/AddPelicula", ReplyAction="http://tempuri.org/IPelicula/AddPeliculaResponse")]
        System.Threading.Tasks.Task AddPeliculaAsync(WEBGCCCine.ServiceReference1.Pelicula pelicula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPelicula/GetFunciones", ReplyAction="http://tempuri.org/IPelicula/GetFuncionesResponse")]
        WEBGCCCine.ServiceReference1.Funciones[] GetFunciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPelicula/GetFunciones", ReplyAction="http://tempuri.org/IPelicula/GetFuncionesResponse")]
        System.Threading.Tasks.Task<WEBGCCCine.ServiceReference1.Funciones[]> GetFuncionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPelicula/addFunciones", ReplyAction="http://tempuri.org/IPelicula/addFuncionesResponse")]
        void addFunciones(WEBGCCCine.ServiceReference1.Funciones funciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPelicula/addFunciones", ReplyAction="http://tempuri.org/IPelicula/addFuncionesResponse")]
        System.Threading.Tasks.Task addFuncionesAsync(WEBGCCCine.ServiceReference1.Funciones funciones);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPeliculaChannel : WEBGCCCine.ServiceReference1.IPelicula, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeliculaClient : System.ServiceModel.ClientBase<WEBGCCCine.ServiceReference1.IPelicula>, WEBGCCCine.ServiceReference1.IPelicula {
        
        public PeliculaClient() {
        }
        
        public PeliculaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeliculaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeliculaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeliculaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WEBGCCCine.ServiceReference1.Pelicula[] GetPeliculas() {
            return base.Channel.GetPeliculas();
        }
        
        public System.Threading.Tasks.Task<WEBGCCCine.ServiceReference1.Pelicula[]> GetPeliculasAsync() {
            return base.Channel.GetPeliculasAsync();
        }
        
        public WEBGCCCine.ServiceReference1.Pelicula GetPelicula(int PeliculaId) {
            return base.Channel.GetPelicula(PeliculaId);
        }
        
        public System.Threading.Tasks.Task<WEBGCCCine.ServiceReference1.Pelicula> GetPeliculaAsync(int PeliculaId) {
            return base.Channel.GetPeliculaAsync(PeliculaId);
        }
        
        public void AddPelicula(WEBGCCCine.ServiceReference1.Pelicula pelicula) {
            base.Channel.AddPelicula(pelicula);
        }
        
        public System.Threading.Tasks.Task AddPeliculaAsync(WEBGCCCine.ServiceReference1.Pelicula pelicula) {
            return base.Channel.AddPeliculaAsync(pelicula);
        }
        
        public WEBGCCCine.ServiceReference1.Funciones[] GetFunciones() {
            return base.Channel.GetFunciones();
        }
        
        public System.Threading.Tasks.Task<WEBGCCCine.ServiceReference1.Funciones[]> GetFuncionesAsync() {
            return base.Channel.GetFuncionesAsync();
        }
        
        public void addFunciones(WEBGCCCine.ServiceReference1.Funciones funciones) {
            base.Channel.addFunciones(funciones);
        }
        
        public System.Threading.Tasks.Task addFuncionesAsync(WEBGCCCine.ServiceReference1.Funciones funciones) {
            return base.Channel.addFuncionesAsync(funciones);
        }
    }
}
